### ISSUE TITLE
K型热电偶问题

### ISSUE THREAD

**Issue by song-hailong** [peng-zhihui/OpenHeat#15]
请问K型热电偶是用来测量铝基板温度还是主控板温度的，应该把K型热电偶固定在哪个位置？

**Comment by peng-zhihui** [comment]
铝基板，买表贴式的贴合就行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: uint8_t ***@***.***&gt;
发送时间: 2021年10月15日 19:20
收件人: peng-zhihui/OpenHeat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/OpenHeat] K型热电偶问题 (#15)





 
请问K型热电偶是用来测量铝基板温度还是主控板温度的，应该把K型热电偶固定在哪个位置？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
